version: "3"

services:
  datastore:
    image: ehacke/datastore-emulator:1.0.1
    environment:
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - "8081:8081"
    command: "--no-store-on-disk --consistency=1.0"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
